---
- name: Install
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  vars:

    role_config: []

  pre_tasks:
  - name: check for file custom_vars.yml
    ansible.builtin.stat:
      path: custom_vars.yml
    register: stat_custom_vars
  - name: load custom vars, if existent
    ansible.builtin.include_vars:
      file: custom_vars.yml
    when: stat_custom_vars.stat.exists

  roles:
  - name: andrelohmann.root_colored_prompt
  - name: ansible-role-__ROLE_NAME__

...
