---
- name: Converge
  hosts: all
  become: true
  become_method: sudo

  vars:
    role_configs: []

  tasks:
  - name: "Include andrelohmann.__ROLE_NAME__"
    include_role:
      name: "andrelohmann.__ROLE_NAME__"
...
