---
- name: Converge
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  vars:
    role_configs: []

  tasks:
  - name: Include andrelohmann.__ROLE_NAME__
    ansible.builtin.include_role:
      name: "andrelohmann.__ROLE_NAME__"
...
